# Woman Cloth Reviews with Multi Nomial  Naive Bayes

# impport lib

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import Dataset

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/YBIFoundation/ProjectHub-MachineLearning/7af39bb0a19a2a7ec76765080d25727a9ba77aff/Women%20Clothing%20E-Commerce%20Review.csv')

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df.shape

(23486, 10)

# Missing Value

In [ ]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [ ]:
df[df['Review']==""]=np.NaN

In [ ]:
df['Review'].fillna("No Review", inplace=True)

In [ ]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [ ]:
df["Review"]

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

# Define Target(Y) and feasture(X)

In [ ]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [ ]:
x=df['Review']

In [ ]:
y=df['Rating']

In [ ]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

# Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y,train_size=0.7,stratify = y,random_state=2529)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

# Get Feature Test Conversion to Tokens

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(lowercase=True,analyzer="word",ngram_range=(2,3),stop_words="english", max_features=5000)

In [ ]:
x_train = cv.fit_transform(x_train)

In [ ]:
cv.get_feature_names_out()

In [ ]:
x_train.toarray()

In [ ]:
x_test = cv.fit_transform(x_test)

In [ ]:
cv.get_feature_names_out()

In [ ]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# Get Model Train

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model = MultinomialNB()

In [ ]:
model.fit(x_train, y_train)

# Get Model Prediction

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
y_pred.shape

(7046,)

In [ ]:
y_pred

array([1., 5., 5., ..., 5., 5., 5.])

# Get Probability of Each Predicted Class

In [ ]:
model.predict_proba(x_test)

array([[0.71118473, 0.02625165, 0.15465118, 0.01496876, 0.09294369],
       [0.02416867, 0.04769471, 0.35268622, 0.16185007, 0.41360034],
       [0.03582725, 0.06660584, 0.12226277, 0.21618005, 0.55912409],
       ...,
       [0.02320281, 0.08950939, 0.08962183, 0.16719203, 0.63047394],
       [0.01167675, 0.00202714, 0.08539004, 0.34347398, 0.55743209],
       [0.03959824, 0.05612822, 0.00688869, 0.1560574 , 0.74132745]])

# Get Model Evaluation

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[  15   13   45   36  144]
 [  43   43   86   85  213]
 [ 116   78  113  166  388]
 [ 166  108  194  336  719]
 [ 371  272  349  722 2225]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.06      0.03       253
         2.0       0.08      0.09      0.09       470
         3.0       0.14      0.13      0.14       861
         4.0       0.25      0.22      0.23      1523
         5.0       0.60      0.56      0.58      3939

    accuracy                           0.39      7046
   macro avg       0.22      0.21      0.21      7046
weighted avg       0.42      0.39      0.40      7046



# Recategories rating as poor (0) and Good(1)

In [ ]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

**Re-Rating as 1,2,3as 0 and 4,5 as 1**

In [ ]:
df.replace({'Rating' : {1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [ ]:
y=df['Rating']

In [ ]:
x=df['Review']

# Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test =train_test_split(x, y, train_size = 0.7, stratify = y, random_state=2529

In [ ]:
 x_train.shape, x_test.shape, y_train.shape, y_test.shape

# Get Feature Text Conversion to Token

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv CountVectorizer(lowercase = True, analyzer ='word', ngram_range(2,3), stop_word ='english', max_features=5000

In [ ]:
x_train=cv.fit_transform(x_train)

In [ ]:
x_test=cv.fit_transform(x_test)


# Get Model Re-Train

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model.fit(x_train,y_train)

# Get Model Prediction

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
y_pred.shape

In [ ]:
y_pred

# 	Get Model Evaluation

In [ ]:
from sklearn.metrics import confution_matrix, classification_report

In [ ]:
print(confution_matrix(y_test,y_pred))

In [ ]:
print(classification_report(y_test,y_pred))